Fixed two bugs related to filtering and distance calculation.
Srekel/the-debuginator pull request #3
Opened 2017-07-01 17:52 UTC by thynnmas

When filtering items with multiline descriptions the height would
be calculated with a hardcoded line count of 1.

If an item was filtered, its height was still counted for distance
to the active item.

2017-07-01 19:41 UTC, Srekel requested changes
This is awesome, thanks for the PR. A few minor comments. If you want to I can accept it as-is and fix it myself, I understand if you feel you have more interesting things to do. :)

2017-07-01 19:41 UTC, Srekel commented on the_debuginator.h
> +		const char* description = item->leaf.description;
Not a fan of creating a new variable with the same name as one in an earlier scope. Maybe just use `item->leaf.description` inside the if?

2017-07-01 19:41 UTC, Srekel commented on the_debuginator.h
> +		float description_width = debuginator->size.x - 50;
Note to self: Expose all of these hard coded constants as overrideable defines.. :)

2017-07-01 19:41 UTC, Srekel commented on the_debuginator.h
> +		} else {
Minor nitpicking :) For the debuginator I put the else { on a new line (so not } else { ).

2017-07-01 19:41 UTC, Srekel commented on the_debuginator.h
> +			} else {
Here too.

2017-07-01 19:41 UTC, Srekel commented on the_debuginator.h
> +int debuginator_total_height(TheDebuginator* debuginator) {
This doesn't seem to get called from this commit. I assume it's needed by something in one of the other PRs? 

Couldn't you simply return total_height for the root item? If not, what's the difference?

2017-07-01 22:06 UTC, thynnmas commented on the_debuginator.h
> +		const char* description = item->leaf.description;
Copy-pasting suck. Yes, should not shadow. 2nd time this year I've accidentally shadowed something :/

2017-07-01 22:08 UTC, thynnmas commented on the_debuginator.h
> +int debuginator_total_height(TheDebuginator* debuginator) {
This is used by the mouse support, and I appear to have messed up including it here. If I recall correctly the reason to use this was that total height was not updated properly when filtered, so I calculated it every time. Now that it _is_ calculated on filtering, using total height on root might work. Would need to test it though, not sure if expanding things properly propagates total height up the tree.

2017-07-01 22:08 UTC, thynnmas commented on the_debuginator.h
> +		} else {
Roger that!

2017-07-01 22:09 UTC, thynnmas commented
I'll look at the clear fixes for most of these tomorrow and see what I can fix, then we can discuss the things that need discussing in person at some point.

2017-07-02 09:33 UTC, Srekel commented on the_debuginator.h
> +int debuginator_total_height(TheDebuginator* debuginator) {
It definitely should. If it didn't then items further down would get rendered in all the wrong places.

2017-07-03 20:07 UTC, merged