Change in an item's filtering state now re-calculates height
Srekel/the-debuginator pull request #4
Opened 2017-07-01 17:53 UTC by thynnmas

Of both itself and it's ancestors, meaning folder-in-folder filtering no longer has long stretches of nothing between items.

2017-07-01 20:43 UTC, Srekel requested changes

2017-07-01 20:43 UTC, Srekel commented on the_debuginator.h
> +			item->total_height = item_height + item_height + item_height * (item->leaf.num_values);
Shouldn't the second item_height be the height of the description?

2017-07-03 20:04 UTC, Srekel requested changes

2017-07-03 20:04 UTC, Srekel commented on the_debuginator.h
> +	debuginator__set_item_total_height_recursively(debuginator->root, debuginator->item_height);
Didn't see this before. debuginator__adjust_num_visible_children gets called for every item that gets filtered away. When you have lots of items it's potentially extremely expensive to do this. Do we need to do it on the root?

2017-07-03 20:42 UTC, thynnmas commented on the_debuginator.h
> +	debuginator__set_item_total_height_recursively(debuginator->root, debuginator->item_height);
It should be enough to call it once on the root _after_ we're done calculating filtering status, but it needs to be done to account for changes to children before you in the tree.

2017-07-04 05:13 UTC, Srekel commented on the_debuginator.h
> +	debuginator__set_item_total_height_recursively(debuginator->root, debuginator->item_height);
Right. Yeah that'd be fine. :)

2017-07-04 18:00 UTC, thynnmas commented on the_debuginator.h
> +	debuginator__set_item_total_height_recursively(debuginator->root, debuginator->item_height);
I had another look, and correct me if I'm wrong, but isn't that what this does? It calls adjust_num_visible_children on the parents of all elements that get filtered (but it kind of has to do that), then does a final (single) set_item_total_height_recursively on the root. Adjusting the child count isn't very expensive (although it is called a lot), and I don't see a simple way around adjusting the final height on the root?

2017-07-04 18:09 UTC, Srekel commented on the_debuginator.h
> +	debuginator__set_item_total_height_recursively(debuginator->root, debuginator->item_height);
Whoops! I misread the diff, it looked like that code was someplace else! :)

2017-07-05 06:14 UTC, Srekel approved these changes

2017-07-05 06:14 UTC, merged