Added mouse support to the stingray plugin.
Srekel/the-debuginator pull request #6
Opened 2017-07-01 17:54 UTC by thynnmas

This includes functions in the debuginator itself to find and select
the closest item to a given height-from-root.

2017-07-01 20:31 UTC, Srekel requested changes

2017-07-01 20:31 UTC, Srekel commented on plugins/stingray/the_debuginator_plugin/c_api_the_debuginator.cpp
> +	float default_focus_height = 0.3f;
Is this needed? Why not use the default in the debuginator?

2017-07-01 20:31 UTC, Srekel commented on plugins/stingray/the_debuginator_plugin/c_api_the_debuginator.cpp
> +			if (scroll.y != 0) {
Sure you don't want to check if the mouse is inside the menu rect?

2017-07-01 20:31 UTC, Srekel commented on plugins/stingray/the_debuginator_plugin/c_api_the_debuginator.cpp
> +				debuginator->focus_height += scroll.y * 0.05f;
I'm not sure about this solution.. The idea with focus_height is to say "I want the hot item to be at 30% from the top of the screen". Modifying it based on scrolling, presumably getting it beyond [0,1] range feels a bit strange..

Wouldn't it be more reasonable to change the hot item? Then everything would be taken care of "automatically".

2017-07-01 20:31 UTC, Srekel commented on the_debuginator.h
> +				if (last_child->leaf.is_expanded) {
This if is the same as the if two lines up, line 2410.

2017-07-01 20:54 UTC, thynnmas commented on plugins/stingray/the_debuginator_plugin/c_api_the_debuginator.cpp
> +			if (scroll.y != 0) {
We catch all input, which is why this felt natural to us (so you could just scroll without paying attention to where the mouse is if you're not using it to play). However I agree that in general you should not take away control when it is open, so it _should_ check for the rect.

2017-07-01 20:57 UTC, thynnmas commented on plugins/stingray/the_debuginator_plugin/c_api_the_debuginator.cpp
> +	float default_focus_height = 0.3f;
I must have missed that there was a default (I only spotted the used focus_height which was constant, but I'm misusing that for scroll now so it changes over time).

2017-07-01 20:58 UTC, thynnmas commented on plugins/stingray/the_debuginator_plugin/c_api_the_debuginator.cpp
> +				debuginator->focus_height += scroll.y * 0.05f;
The usage request was "I want to be able to scroll, then if I don't click something and press a up I should go one up from the old selection, like a text-editor or file explorer would", which is why I'm doing this. It feels weird that the focus_height is outside [0,1] range and we're focusing the view around a hot item that's not on screen; probably rather want a view-offset and let the focus height be constant.

2017-07-02 09:47 UTC, Srekel commented on plugins/stingray/the_debuginator_plugin/c_api_the_debuginator.cpp
> +	float default_focus_height = 0.3f;
There's the one in the default config thing. It should really be added to DebuginatorPluginCreateContext and then you can store the app's wanted default value in this function similar to how other config variables are done:

TheDebuginator* create_debuginator(const char* id, DebuginatorPluginCreateContext* context) {

2017-07-02 09:59 UTC, Srekel commented on plugins/stingray/the_debuginator_plugin/c_api_the_debuginator.cpp
> +				debuginator->focus_height += scroll.y * 0.05f;
Right, ok that makes sense. :)

If it's ok with you, I'll accept this after you fix the other issues, but there are some things I think I would like to change with how this is done. I want to move some of the functionality to The Debuginator. I don't want each app to have to reinvent how to do mouse-input.

2017-08-07 05:28 UTC, Srekel requested changes
Since I've now added a mouse support API, please use that instead. Let me know if you have any issues with it. You can check the SDL demo for examples of how to use it :)

2018-04-30 08:48 UTC, Srekel commented
I'm going to close this, but feel free to open a new one after you've updated to the new input API, if you needed to make any changes.  :)

2018-04-30 08:48 UTC, closed without merging